ARG FROM=trophime/salome:9.11.0-debian11

FROM ${FROM}

ARG DEBUG=1

ARG NUMTHREADS=1
ARG TERM=linux
ARG DEBIAN_FRONTEND=noninteractive
ARG DESTDIR=/opt
ARG VERSION=9.11.0
ARG PLATFORM=DB11

USER root

# Setup demo environment variables
ENV LANG=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8 \
    DISPLAY=:0.0 \
    DISPLAY_WIDTH=1024 \
    DISPLAY_HEIGHT=768 \
    RUN_XTERM=yes \
    RUN_FLUXBOX=yes \
    PATH=${DESTDIR}/SALOME-${VERSION}-${PLATFORM}:${DESTDIR}/SALOME-${VERSION}-${PLATFORM}/sat:$PATH

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# Install git, supervisor, VNC, & X11 packages
RUN apt-get -qq update && \
    apt-get -y upgrade && \
    apt install -y \
        procps net-tools \
	      wget curl \
	      emacs-nox vim nano \
	      lsb-release \
	      bash  bash-completion \
	      fluxbox \
	      git \
	      net-tools \
	      novnc \
	      supervisor \
	      x11vnc \
	      xterm \
	      xvfb \
        mesa-utils mesa-utils-extra && \
    apt clean -y
    

# Install vglrun?
RUN wget -qO- https://www.virtualgl.org/key/VGL-GPG-KEY  | gpg --dearmor > VGL-GPG-KEY \ 
    && install -D -o root -g root -m 644 VGL-GPG-KEY /etc/apt/keyrings/virtualgl.gpg \
    && apt-get -y update \
    && apt-get -y install libegl1-mesa \
    && wget https://sourceforge.net/projects/virtualgl/files/3.1/virtualgl_3.1_amd64.deb/download -O /tmp/virtualgl_3.1_amd64.deb \
    && dpkg -i /tmp/virtualgl_3.1_amd64.deb \
    && rm /tmp/virtualgl_3.1_amd64.deb
    
# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog

COPY . /app
CMD ["/app/entrypoint.sh"]
EXPOSE 8080


